---
- name: uninstalling httpd
  hosts: all
  become: true
  tasks:
  - name: Stop  httpd        
    service:
      name: httpd
      state: stopped

  - name: Uninstalling httpd
    yum:
      name: httpd
      state: removed

